# Generated by Django 4.1.2 on 2022-10-07 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Women',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('content', models.TextField(blank=True, verbose_name='Информация')),
                ('photo', models.ImageField(upload_to='photo/%Y/%m/%d', verbose_name='Фото')),
                ('price', models.FloatField(max_length=20, verbose_name='Цена')),
                ('size', models.CharField(max_length=4, verbose_name='Размер')),
                ('brand', models.CharField(max_length=255, verbose_name='Брэнд')),
                ('designer', models.CharField(max_length=255, verbose_name='Дизайнер')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('publish', models.BooleanField(default=True, verbose_name='Публикация')),
            ],
        ),
    ]
