# Generated by Django 4.1.2 on 2022-10-07 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='women',
            options={'ordering': ['time_create', 'title'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Магазин Одежды'},
        ),
        migrations.RemoveField(
            model_name='women',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='women',
            name='designer',
        ),
        migrations.RemoveField(
            model_name='women',
            name='size',
        ),
    ]
