# Generated by Django 4.1.2 on 2022-10-07 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_brand_alter_women_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='women',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.brand', verbose_name='Брэнд'),
        ),
    ]
