# Generated by Django 4.1.2 on 2022-10-09 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_women_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='women',
            name='old',
            field=models.CharField(max_length=255, null=True, verbose_name='Пол'),
        ),
    ]
