# Generated by Django 4.1.2 on 2022-10-09 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_women_old'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='women',
            name='old',
        ),
    ]
