# Generated by Django 4.1.2 on 2022-10-10 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_gender_women_gender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gender',
            options={'ordering': ['id'], 'verbose_name': 'Гендэр', 'verbose_name_plural': 'Гендэр'},
        ),
        migrations.AlterField(
            model_name='gender',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Гендэр'),
        ),
    ]
