# Generated by Django 4.1.2 on 2022-10-13 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_women_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='women',
            name='slug',
        ),
    ]
