# Generated by Django 4.1.2 on 2022-10-17 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_remove_women_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='SortProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, null=True, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Сортировка',
                'verbose_name_plural': 'Сортировка',
                'ordering': ['id'],
            },
        ),
    ]
