# Generated by Django 4.1.2 on 2022-11-03 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_brand_slug_alter_carz_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='women',
            name='courses',
            field=models.ManyToManyField(to='shop.colorproduct'),
        ),
    ]
