# Generated by Django 4.1.2 on 2022-11-03 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_women_courses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='women',
            old_name='courses',
            new_name='colors',
        ),
    ]
