# Generated by Django 4.1.2 on 2022-11-11 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_women_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='women',
            name='category',
            field=models.CharField(choices=[('accessories', 'Аксессуары'), ('bags', 'Рюкзаки'), ('hoodies_or_sweatshirts', 'Толстовки или свитшоты'), ('jackets_or_coats', 'Куртки или пальто'), ('polos', 'Поло'), ('shirts', 'Рубашки'), ('shoes', 'Обувь'), ('sweaters', 'Свитера'), ('t_shirts', 'Футблоки'), ('trousers_or_jeans', 'Брюки или джинсы')], max_length=30, null=True, verbose_name='Категория'),
        ),
    ]
