# Generated by Django 4.1.2 on 2023-01-19 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_alter_women_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='women',
            name='sizes',
            field=models.ManyToManyField(to='shop.sizeproduct'),
        ),
    ]
